project:
  type: website

website:
  title: "flashr decks"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - decks.qmd
      - contribute.qmd
    right:
      - icon: "github"
        href: "https://github.com/jeffreyrstevens/flashr_decks"
  repo-url: https://github.com/jeffreyrstevens/flashr_decks
  repo-actions: [issue]

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual
