project:
  type: website

website:
  title: "flashr decks"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - decks.qmd
      - contribute.qmd
      - href: functions.qmd
        text: Functions
    right:
      - icon: "github"
        href: "https://github.com/jeffreyrstevens/flashr_decks"
  repo-url: https://github.com/jeffreyrstevens/flashr_decks
  repo-actions: [issue]
  page-footer: 
    left: "Copyright 2024, Jeffrey Stevens" 
    right: 
      - icon: github
        href: https://github.com/jeffreyrstevens/flashr_decks


format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual
