# Contributing decks

Feel free to propose new decks to contribute to flashr_decks. It makes most sense to post decks that other people might be interested in using---for example, based on books or publicly available resources. The best way to do this is to create the CSV files for the decks and [submit a pull request](https://github.com/JeffreyRStevens/flashr_decks/pulls). To create the CSV files, create columns titled `term`, `description`, `package`, and `title` (optional). Then fill in these columns with the terms, descriptions, and packages that you would like included in your flashcards. Check out the [flashr documentation](https://github.com/JeffreyRStevens/flashr_decks/pulls) for more details on creating decks. Please keep file names short and consistent (e.g., `r2ds01.csv` for functions from *R for Data Science* Chapter 1).

Feel free to [contact me](mailto:jeffrey.r.stevens@protonmail.com) to check if a deck idea makes sense for this repository or if you have questions about building decks. Once the decks are built, submit a pull request to add them to the `decks/` directory of this repository. Note, all decks posted here (included contributed decks) are published under the [MIT license](LICENSE.md) and contributors of decks must abide by the project's [code of conduct](code_of_conduct.md).

## Code of Conduct

Please note that the flashr decks project is released with a [contributor code of conduct](code_of_conduct.md).

By participating in this project you agree to abide by its terms.

#