---
output:
  md_document
---

# Welcome to the flashcard deck repository for flashr

This is the repository of flashcard decks for the [flashr](https://github.com/JeffreyRStevens/flashr) R package. Check out the categories of decks below or look in the `decks/` directory for individual decks.

## Available decks

<details><summary><a href = "https://r4ds.had.co.nz">R for Data Science</a> (1st edition)</summary>
* Ch. 1 Introduction: `r4ds1`
* Ch. 3 Data visualization: `r4ds3`
* Ch. 5 Data transformation: `r4ds5`
* Ch. 7 Exploratory data analysis: `r4ds7`
* Ch. 8 Workflow: projects: `r4ds8`
</details>

<details><summary><a href="https://psyteachr.github.io/quant-fun-v2/">PsyTeachR Fundamentals of Quantitative Analysis</a> decks</summary>
* Ch. 1 Programming basics: `psyteachr_ads1`
* Ch. 2 Intro to R: `psyteachr_ads2`
* Ch. 3 Starting with data: `psyteachr_ads3`
* Ch. 4 Data wrangling 1: `psyteachr_ads4`
* Ch. 5 Data wrangling 2: `psyteachr_ads5`
* Ch. 6 Data wrangling 3: `psyteachr_ads6`
* Ch. 7 Intro to data visualisation: `psyteachr_ads7`
* Ch. 8 Probability: `psyteachr_ads8`
* Ch. 9 Correlations: `psyteachr_ads9`
* Ch. 10 t-tests: `psyteachr_ads10`
* Ch. 11 Power and effect sizes: `psyteachr_ads11`
* Ch. 12 Screening data: `psyteachr_ads12`
* Ch. 13 Visualisation: `psyteachr_ads13`
* Ch. 14 One-way ANOVA: `psyteachr_ads14`
* Ch. 15 Factorial ANOVA: `psyteachr_ads15`
* Ch. 16 Regression: `psyteachr_ads16`
* Ch. 17 Multiple regression: `psyteachr_ads17`
</details>

<details><summary><a href="https://psyteachr.github.io/reprores-v2/">PsyTeachR Data Skills for Reproducible Research</a> decks</summary>
* Ch. 1 Getting started: `psyteachr_dsrr1`
* Ch. 2 Reproducible workflows: `psyteachr_dsrr2`
* Ch. 3 Data visualisation: `psyteachr_dsrr3`
* Ch. 4 Working with data: `psyteachr_dsrr4`
* Ch. 5 Data relations: `psyteachr_dsrr5`
* Ch. 6 Tidy data: `psyteachr_dsrr6`
* Ch. 7 Data wrangling: `psyteachr_dsrr7`
* Ch. 8 Introduction to GLM: `psyteachr_dsrr8`
* Ch. 9 Iteration & functions: `psyteachr_dsrr9`
* Ch. 10 Probability & simulation: `psyteachr_dsrr10`
</details>

<details><summary><a href="https://psyteachr.github.io/ads-v1/">PsyTeachR Applied Data Skills</a> decks</summary>
* Ch. 1 Intro to R and RStudio: `psyteachr_ads1`
* Ch. 2 Reports with R Markdown: `psyteachr_ads2`
* Ch. 3 Data visualisation: `psyteachr_ads3`
* Ch. 4 Data import: `psyteachr_ads4`
* Ch. 5 Data summaries: `psyteachr_ads5`
* Ch. 6 Practice report: `psyteachr_ads6`
* Ch. 7 Data replations: `psyteachr_ads7`
* Ch. 8 Data tidying: `psyteachr_ads8`
* Ch. 9 Data wrangling: `psyteachr_ads9`
* Ch. 10 Customising visualisations & reports: `psyteachr_ads10`
</details>

<details><summary>Miscellaneous decks</summary>
* Data types: `data_types`
* Operators: `operators`
* Vectors: `vectors`
</details>

<!-- ### [R for Data Science](https://r4ds.had.co.nz) (2nd edition), category ID `r4ds2e` -->

## Proposing decks

Feel free to propose new decks. It makes most sense to post decks that other people might be interested in using---for example, based on books or publicly available resources. The best way to do this is to create the CSV files for the decks and submit a pull request. To create the CSV files, create columns titled `term`, `description`, `package`, and `title` (optional). Then fill in these columns with the terms, descriptions, and packages that you would like included in your flashcards. Check out the flashr documentation for my details on creating decks. Please keep file names short and consistent (e.g., `r2ds1.csv` for functions from *R for Data Science* Chapter 1).

Feel free to [contact me](mailto:jeffrey.r.stevens@protonmail.com) to check if a deck idea makes sense for this repository or if you have questions about building decks. Once the decks are built, submit a pull request to add them to the `decks/` directory of this repository. Note, all decks posted here (included contributed decks) are published under the [MIT license](LICENSE.md) and contributors of decks must abide by the project's [code of conduct](code_of_conduct.md).

## Code of Conduct

Please note that the flashr decks project is released with a [contributor code of conduct](code_of_conduct.md).

By participating in this project you agree to abide by its terms.

## License

This repository is licensed under the MIT license. See the [`LICENSE.md`](LICENSE.md) file for more details.
